[package]
name = "halloween"
version = "0.1.0"
authors = [
    "Christoph Kappel <christoph@unexist.dev>"
]
edition = "2024"
description = "Halloween webpage"
readme = "README.adoc"
repository = "https://hg.unexist.dev/halloween"
license = "GPL-3"
keywords = ["yew", "trunk"]
categories = ["gui", "wasm", "web-programming"]

[dependencies]
yew = { version="0.21", features=["csr"] }
