version: '3'

tasks:
  serve:
    cmds:
      - trunk serve

  test:
    cmds:
      - cargo test -- --nocapture {{.CLI_ARGS}}

  clean:
    cmds:
      - cargo clean

  release:
    cmds:
      - trunk serve --release

